# Generated by Django 5.0.4 on 2024-05-23 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialsApp', '0003_alter_lesson_course_subscription'),
        ('paymentApp', '0002_rename_pyment_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Укажите курс', null=True, on_delete=django.db.models.deletion.SET_NULL, to='materialsApp.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='payment',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Укажите урок', null=True, on_delete=django.db.models.deletion.SET_NULL, to='materialsApp.lesson', verbose_name='Урок'),
        ),
    ]
