# Generated by Django 5.0.4 on 2024-04-26 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materialsApp', '0002_alter_course_image'),
        ('usersApp', '0002_user_avatar_user_city_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_payment', models.DateTimeField(auto_now=True, verbose_name='Дата оплаты')),
                ('sum_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма оплаты')),
                ('method_paid', models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод на счет')], max_length=30, verbose_name='Способ оплаты')),
                ('paid_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Оплаченный_курс', to='materialsApp.course')),
                ('paid_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Оплаченный_урок', to='materialsApp.lesson')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Пользователь', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
