# Generated by Django 5.0.4 on 2024-04-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0003_payments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ('at_payment',), 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
    ]
